export type RootStackParamList = {
  Login: undefined;
  Home: undefined;
  Services: undefined;
  Bills: undefined;
  BillDetail: { bill: any };
  PaymentDetail: { bill: any };
  TransactionHistory: undefined;
  BuildingList: undefined;
  RoomList: { id: string; name: string };
  RequestHistory: undefined;
  RequestDetail: { id: string };
  CreateRequest: undefined;
  Notifications: undefined;
  NotificationDetail: { id: string };
  ManagerHome: undefined;
  Settings: undefined;
  Profile: undefined;
  ChangePassword: undefined;
  RegisterAccommodation: undefined;
  ExtendAccommodation: undefined;
  RegularRequest: undefined;
  SpecialRequest: undefined;
  RoomMembers: undefined;
  StudentList: undefined;
  ManagerBills: undefined;
  ManagerSpecialRequest: undefined;
  ManagerSpecialRequestDetail: { id: string };
  ManagerNotifications: undefined;
  ManagerNotificationDetail: { id?: string };
  ManagerRegularRequest: undefined;
  ManagerServices: undefined;
  ManagerTerm: undefined;
  ManagerTermDetail: { mode: "create" | "edit"; term?: any };
  RecordMeterReading: { period: string };
};
